# Generated by Django 3.0.5 on 2020-04-02 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='sub_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_sub_category', to='blog.PostSubCategory'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='blog.PostCategory'),
        ),
    ]
