# Generated by Django 3.0.5 on 2020-04-02 19:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200403_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='postsubcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='tag', unique=True),
        ),
    ]
