# Generated by Django 3.0.5 on 2020-04-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200403_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(default=None, null=True, to='blog.PostTag'),
        ),
    ]
