# Generated by Django 3.0.5 on 2020-04-03 17:25

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200403_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default=None, null=True, upload_to='post-images'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default=None, null=True, upload_to='post-images/thumbnails'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='blog.PostTag'),
        ),
    ]
